---

- name: Build the image for dns server
  docker_image:
    name: dns_server
    tag: 1.0
    build:
      path: /root/DNS_SERVER/Python-DNS-Server/Docker/DNS_Docker


- name: Build the image for flask API
  docker_image:
    name: flask_api
    tag: 1.0
    build:
      path: /root/DNS_SERVER/Python-DNS-Server/Docker/Exporter_Docker


- name: Build the image for the exporter
  docker_image:
    name: dns_exporter
    tag: 1.0
    build:
      path: /root/DNS_SERVER/Python-DNS-Server/Docker/Flask_Docker






