---
- name: setting up a DNS server with API and external exporter
  hosts: all
  become: true
  tasks:
    - name: Setting up the basis
      include_role:
        name: "{{ item }}"
      with_items:
        - /root/DNS_server/Python-DNS-Server/Ansible/roles/pre_set_up
        - /root/DNS_server/Python-DNS-Server/Ansible/roles/clone_the_code
        - /root/DNS_server/Python-DNS-Server/Ansible/roles/install_docker


    - name: set up the DNS server
      include_role:
        name: "{{ item }}"
      with_items:
        - /root/DNS_server/Python-DNS-Server/Ansible/roles/build_images
        - /root/DNS_server/Python-DNS-Server/Ansible/roles/run_applications


