---
- name: setting up a DNS server with API and external exporter
  hosts: all
  become: true
  tasks:
    - name: Setting up the basis
      include_role:
        name: "{{ item }}"
      with_items:
        - /root/DNS_SERVER/ansible/k8s/roles/pre_setup
        - /root/DNS_SERVER/ansible/k8s/roles/clone_the_code
        - /root/DNS_SERVER/ansible/k8s/roles/install_docker
  

    - name: set up the DNS server
      include_role:
        name: "{{ item }}"
      with_items:
        - /root/DNS_SERVER/ansible/k8s/roles/build_images
        - /root/DNS_SERVER/ansible/k8s/roles/run_application


